/**:
  ros__parameters:
    pointcloud2_filter_chain:
      filter1:
        name: deskewLinear
        type: filters_pointcloud2_erdc/DeskewLinear
        params:
          map_frame_id: odom
          field: t
          conversion: 1.0
          frequency: 10.0
