/**:
  ros__parameters:
    pointcloud2_filter_chain:
      filter1:
        name: deskewImu
        type: filters_pointcloud2_erdc/DeskewImu
        params:
          map_frame_id: odom
          robot_frame_id: base_footprint
          field: t
          conversion: 1.0
          frequency: 10.0
          
          imu_topic: "/sensors/imu/sensor1/imu/data"
          imu_buffer_size: 2000
          gravity: 9.80665
      

