/**:
  ros__parameters:
    pointcloud2_filter_chain:
      filter1:
        name: field_value_filter
        type: filters_pointcloud2_erdc/FieldValueFilter_Integer
        params:
          frame_id: ""
          field: "intensity"
          min: 0
          max: 100
          keep_organized: False
          invert: True
