/**:
  ros__parameters:
    pointcloud2_filter_chain:
      filter1:
        name: flip_rings
        type: filters_pointcloud2_erdc/FlipRings
        params:
          field: "ring"
          num_rings: 64
